pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install bundler
    - gem install jekyll 
    - bundle install
    - jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master
