# Conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            'Living life and Make it Better'
tagline:          'life, learn, contribute'
description:      'learns software development, java programming, android, linux, and other open source technology'
url:              http://software.endy.muhardin.com

author:
  name:           Endy Muhardin
  email:          endy.muhardin@gmail.com
  github:         endymuhardin
  twitter:        endymuhardin
  linkedin:       endy-muhardin
  facebook:       endy.muhardin
  url:            http://endy.muhardin.com
  email_md5:      a3c8a6a973fc0c0fa3d89cb69c103ad0
  bio:            Software Developer berdomisili di Jabodetabek, berkutat di lingkungan open source, terutama Java dan Linux.

gems: 
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

paginate:         5

# Google Analytics
google_analytics_tracking_id: UA-36102948-1

# Facebook Comments
facebook_appid: 269506799827290
